# Project: Name
# Website: http://herenkeskin.com
# Github:  http://github.com/erenkeskin
# Makefile created by Hasan Eren Keskin

CPP      = g++.exe
CC       = gcc.exe
RM       = rm.exe -f

FILE_NAME = queue

clean:
	${RM} $(OBJ) $(BIN)

compile: 
	${CPP} -o ${FILE_NAME} ${FILE_NAME}.cpp

run: 
	${FILE_NAME}.exe